### ISSUE TITLE
MacOS static binaries

### ISSUE THREAD

**Issue by aymanbagabas** [tsl0922/ttyd#1011]
**Is your feature request related to a problem? Please describe.**
The releases page lacks a Darwin statically linked MacOS binaries.

**Describe the solution you'd like**
Build for Darwin/MacOS

**Comment by tsl0922** [comment]
Sorry, no plan for it, PRs are welcomed.

If you have trouble with brew on MacOS Ventura, check https://github.com/orgs/Homebrew/discussions/3822

**Comment by ofcRS** [comment]
## ttyd builds cleanly from source on macOS (no Homebrew needed)

Thanks for leaving the door open with "no plan, but PRs welcome" — totally understand the stance. Wanted to share a concrete data point for anyone who lands here wanting macOS binaries.

**ttyd builds cleanly from source on macOS.** I verified a from-source 1.7.7 build on Apple Silicon (arm64): the third-party deps (OpenSSL 3.6.1, libwebsockets 4.5.7, libuv 1.52.1, json-c 0.18) link **statically from source**, zlib resolves to the macOS system `libz`, and `otool -L` on the result shows only macOS system libraries — `CoreFoundation`, `CoreServices`, `IOKit`, `/usr/lib/libz`, `/usr/lib/libutil`, `/usr/lib/libSystem`. (System `libz`/`libSystem` staying dynamic is normal and unavoidable on macOS, which ships no static `libSystem`.) So the binary is self-contained with respect to third-party code.

The recipe mirrors `scripts/cross-build.sh` — same pinned dep versions, same libwebsockets flag set — with only the macOS-specific swaps: native clang instead of musl, OpenSSL `darwin64-{arm64,x86_64}-cc`, BSD `sed -i ''`, and (since `-static` is impossible on macOS) `-framework CoreFoundation -framework CoreServices -framework IOKit -Wl,-dead_strip` in place of `-static`, then `strip -S`. Full self-contained script + notes here: https://gist.github.com/ofcRS/4efc3b945765e7b4b1ff432c439dd460

I went ahead and opened #1553 with exactly this — a native `macos` job in `backend.yml` (a `macos-14` + `macos-13` matrix, same `ttyd.<target>` artifact convention, so it slots into the existing `release.yml` publish step with no changes there) plus a short build guide, following the precedent of the existing native `msvc` job. Totally happy to close it or scope it down to docs-only if you'd rather — no pressure to merge.

One honest caveat worth deciding up front: **CI-built binaries would be unsigned and un-notarized**, so anyone downloading them from Releases hits Gatekeeper ("cannot be opened" / "is damaged") until they run `xattr -d com.apple.quarantine ttyd` (or right-click → Open once). Real signing/notarization needs *your* Apple Developer ID + CI secrets — a contributor can't supply that, and I wouldn't want to imply the artifacts are signed when they aren't. Locally built binaries aren't affected.

Would you prefer (a) CI-built unsigned binaries with a clear quarantine note, (b) docs-only build instructions, or (c) not worth it right now? Happy to follow your call — and happy to drop the Intel leg if the `macos-13` runner retirement makes it not worth maintaining.
