### ISSUE TITLE
ttyd crashes on windows

### ISSUE THREAD

**Issue by tech128** [tsl0922/ttyd#1292]
**Describe the bug**

**To Reproduce**
1. run ttyd.win32.exe cmd
2. open browser and enter in the ip address:7681
3. ttyd exits with either "== CreateProcessW failed with error 267: The directory name is invalid." or just nothing at all

**Expected behavior**
Expected to see a command prompt in the browser when I connect to the port.

**Screenshots**
N / A

**Environment:**
 - OS: Windows 10 and Windows 11
 - Browser: Edge 121.0.2277.83 (Official build) (64-bit) 

**Additional context**
I traced it with process monitor and see it tries to reference some weird directory with chinese characters for some odd reason.  I created this directory but it still does not fix the crash.  Something is causing the crash right when it tries to run the command.

**Comment by tsl0922** [comment]
It has nothing to do with ttyd, you may have other file named as `cmd`, trying using full path like:

```
ttyd.win32.exe C:\Windows\System32\cmd.exe
```

**Comment by tech128** [comment]
Nope, still the same issue.  I should have listed that in the report, but I figured you would look into it.

Just fyi, I'm not a noob who doesn't know if something is a bug or not.

If I post a report, trust me, it's a bug.

I go to great lengths to make sure its not really something I've done wrong somehow.

**Comment by tsl0922** [comment]
The error you encountered is returned from windows API, you may google it yourself.

**Comment by tech128** [comment]
Well I did more than that, I did a lot of testing against the current and older versions and found that version 1.7.3 works fine on both.  This report shows my exact issue.

https://github.com/tsl0922/ttyd/issues/1207

I would have found it if it had a better title.

Thank you for writing this software, I use it as a quick form of remote access and also works well when the customer is still using his machine.

**Comment by dna2github** [comment]
i met the same problem @tech128 
and i tried to set cwd like `-w c:\` then it works ...

**Comment by awesomemad** [comment]
i have the same problunixem too, it is probably becuase of that at unix envarionments your root directory is / and it expects that, and since your windows directory doont htave that / as rott directory, it is assuming that there is a subdirectory called c:\ in the current directory, try it with msys2 or cygwin or any other unix envarionment for windows i would say, but no, even that didnt work out for me, but if the issue is the same that issue, it should work when you are at the rott directroy and type type the subfolder directory of the cli tool but no, that too didnt work, eventually i have no idea what is haooening about this, still, probably a conflict between the unix envarionments this has deigned for and the windows envarionment, but i have no idea except than that

EDIT:  i saw that for running the thing in a special directory you need to specify it with the -w flag, i ran at my home directory and fşf soecify the executable from as ..\..\windows\system32\cmd and it worked, therefore it id the thing that i said earlier, it sees c:\ as a subdirectory since it confilcts between the unix and windows envarionments. so you need to specify a working directory, and than specify the executable with subdirectories, hope this helps

**Comment by Sorcerio** [comment]
Definitely still an issue.

This will work as a work around: `ttyd -W -w "C:\Users\YOUR_WINDOWS_USER_NAME\Desktop\" -p 7681 "powershell.exe"`
Trying to include anything like `%USERPROFILE%\Desktop` or `~\Desktop` _will not work_. It seems like it has to be a direct, full, absolute path.
