### ISSUE TITLE
Forward specific keyboard shortcuts

### ISSUE THREAD

**Issue by realies** [tsl0922/ttyd#164]
Recently noticed that whenever using keyboard shortcuts such as `ctrl+w`, most browsers would like to close the browser window on focus, although the shortcut is useful some terminal CLIs. Perhaps not as specific to `ttyd`, wondering if there's any way to forward these?

**Comment by tsl0922** [comment]
This is already handled in ttyd by capturing the `beforeunload` event, if you press `Ctrl+W` on a opened ttyd session, the browser should give you a confirm prompt.

If `Ctrl+W` is pressed quickly after ttyd page opened, you may not get the prompt since the event handler is registered after ttyd's session initialized.

**Comment by SuperSandro2000** [comment]
I don't think you answered his question. Eg I can't use nano search without remapping it in ttyd.

**Comment by tsl0922** [comment]
@SuperSandro2000 I'm afraid browsers like chrome still doesn’t allow disabling or remapping hot keys like `Ctrl + W`:

https://bugs.chromium.org/p/chromium/issues/detail?id=119881

**Comment by SuperSandro2000** [comment]
Thanks for the answer. Could there be an option to use some "compose" key to emulatre Ctrl + W?
