### ISSUE TITLE
—url-arg issue

### ISSUE THREAD

**Issue by bawa3436** [tsl0922/ttyd#249]
Im trying to set up a ttyd with console app using docker image and im getting error while using the —url-arg

Im running the docker container:

`docker run tsl0922/ttyd —url-arg bash`

When the container starts i see in the logs that the allow url arg flag is set to true

But every time im using the browser to use the console application like this:
`localhost:7681/?arg=foo`

The process of the console application is crashing with an exit code of 127 (command not found)

When im using the browser without any url params like this:
`localhost:7681/`
the app is running just fine (but off course without any args)

**Comment by fbartels** [comment]
I was experimenting with arguments as well and stumbled upon your issue. For me it feels a bit like this is by design.

Some clearer steps to your description:
- run with `docker run -it -p 7681:7681 tsl0922/ttyd ttyd --url-arg bash`
- call localhost:7681/ -> no problem bash is loaded
- call localhost:7681/?arg=echo -> browser prints `/bin/echo: /bin/echo: cannot execute binary file`
- call localhost:7681//?arg=-v -> bash is started with the `-v` argument

This sounds a bit like "by design" to me. passing on arguments via a url parameter will simply add arguments to the program call. Like when your program is `apt` and you pass the argument `update`.

**Comment by tsl0922** [comment]
Thanks @fbartels . It's by design, you can't change the command it self via the `--url-arg` argument.
