### ISSUE TITLE
Want have a command line client like gotty-client

### ISSUE THREAD

**Issue by mickey50** [tsl0922/ttyd#595]
Gotty have a client but do not support ZModem to receive/send files ，If have this ，ttyd can use as a command line tools . thx !

**Comment by Depau** [comment]
Here you go: https://github.com/Depau/ttyc.git

I actually made it for https://github.com/Depau/wi-se-sw/ , which is an ESP8266 firmware I'm working on that exposes the UART console with a ttyd-compatible WebSocket protocol (and the same web UI). So you'll find some additional options to set UART parameters which you can ignore.

It's still a WIP so suggestions are welcome, expect bugs. There's no README yet but you can clone it, then 

```bash
cd ttyc/cmd/ttyc
go build
./ttyc --help
./ttyc --host localhost --port 7681
```

It will then expose an interface very similar to [tio](https://github.com/tio/tio), which happens to be my tty terminal of choice. So press Ctrl+T followed by Q to exit, followed by ? for help.

It does not support ZModem and since I'm not interested in the feature I won't probably work on it, but PRs are welcome.

However, you can also run it with `--tty /path/to/file`, it will create a pseudo-terminal and link it to that location, then you can connect it using another terminal program such as minicom, `minicom -D /path/to/file`, and use zmodem or any other protocol you like (terminal resizing won't work, but you can use the `resize` tool included with `xterm`).

**Comment by tsl0922** [comment]
Thank yo @Depau
