### ISSUE TITLE
TERM is not set when used as systemd service 

### ISSUE THREAD

**Issue by qiqian** [tsl0922/ttyd#710]
systemd config as below:
[Unit]
Description=ttyd
After=network.target ypbind.service sssd.service network-online.target remote-fs.target
Wants=network-online.target

[Service]
ExecStart=/usr/local/bin/ttyd -t TERM=xterm-256color -p 7903 ssh test@192.168.10.100
ExecStop=/usr/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
Type=simple

[Install]
WantedBy=multi-user.target

**To Reproduce**
when start ttyd as a systemd service, after connected to the ssh server, no TERM variable is set, thus 'top' doesn't work
if I start ttyd using "/usr/local/bin/ttyd -t TERM=xterm-256color -p 7903 ssh test@192.168.10.100" directly, TERM would be set  

**Expected behavior**

**Screenshots**

**Environment:**
192.168.10.100 is Mac OS X big sur 11.4
ttyd 1.6.3-23ed8d1 run in "Linux raspberrypi 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux"

**Additional context**

**Comment by qiqian** [comment]
if i set terminal by typing "TERM=xterm-256color" in web terminal,

echo $TERM
xterm-256color

then top, it says
Error opening terminal: unknown

**Comment by solarispika** [comment]
I had the same issue as described in https://github.com/tsl0922/ttyd/issues/672#issuecomment-849579000 .

**Comment by gsperry** [comment]
ttyd uses the user session of the process in which it is spawned. To get it to work as a service, you need to provide it a session environment. This can be done in two ways
1. Use the `bash` start command instead of login. This works well and immediately gives a full terminal session for whichever user is set in the ttyd systemd service config. Unfortunately, eliminates the likely desirable necessity of forcing a login. Note: you cannot issue the `login` start command under any user other than root.
2. Have loginctl allow root sessions to linger using the command `# loginctl enable-linger root`. This means that the root user always has a user session running. When the `login` start command is run as root by systemd, it will run in the root user session and provide a full terminal environment to ttyd. While this does expose a root session to the open port, it only does so to force a login, so it is still secure.

**Comment by gsperry** [comment]
ttyd uses the user session of the process in which it is spawned. To get it to work as a service, you need to provide it a session environment. This can be done in two ways
1. Use the `bash` start command instead of `login`. This works well and immediately gives a full terminal session for whichever user is set in the ttyd systemd service config. Unfortunately, this eliminates the likely desirable functionality of forcing a login.
2. Have loginctl allow root sessions to linger using the command `# loginctl enable-linger root`. This means that the root user always has a user session running. When the `login` start command is run as root by systemd, it will run in the root user session and provide a full terminal environment to ttyd. While this does expose a root session to the open port, it only does so to force a login, so it is still secure.

Note: you cannot issue the `login` start command under any user other than root. This is why it must be a root session that is allowed to linger.

**Comment by tsl0922** [comment]
Have you tried if the [1.6.3](https://github.com/tsl0922/ttyd/releases/tag/1.6.3) version works?

I believe the code on master forget to set the `TERM` env when spawning pty process, will fix it later.

**Comment by tsl0922** [comment]
Fixed on master via 619bfc34cd11d67956deda83e6447fcf1c223373
