### ISSUE TITLE
Is there any way to remain the work progress after browser refresh

### ISSUE THREAD

**Issue by yihaoye** [tsl0922/ttyd#741]
For example, if I am using vim editing a file in the web shell, and I refresh the web page, is there any way to still keep me in the vim?

**Comment by nlvw** [comment]
The answer is instead of having ttyd launch '/bin/bash' have it launch tmux instead.

```shell
ttyd -p 8080 -c "ttyd:password123" tmux new -A -s "ttyd_session"
```

On page refresh only the tmux frontend/client will be reloaded while the actual tmux session is persisted.  The above command will reattach to the session if it already exists and if not then create a new session.
