### ISSUE TITLE
Document how to set terminal options such as rows, columns and background

### ISSUE THREAD

**Issue by vsipuli** [tsl0922/ttyd#79]
Suggestion for enhancement: Looking at the command-line options, it is not evident how to set terminal options such as the number of rows, columns and the background color or theme. Would it be possible to clarify this? There is `--client-option`, but it is not entirely clear what the possible values for it are. Thank you.

**Comment by tsl0922** [comment]
You can check the available options here: https://xtermjs.org/docs/api/terminal/#options.

BTW: setting the number of rows, columns makes no sense because terminal will auto resize while the browser window resizing.

The background color or theme is not configurable directly via command-line option, but you can provide you own `index.html` via the `--index` option. Source of `index.html` is under the [html](https://github.com/tsl0922/ttyd/tree/master/html) directory, modify it and build your own.

**Comment by vsipuli** [comment]
Thanks for the link to the available options. Regarding terminal rows and columns: is it possible to disable autoresizing somehow? It would be useful to be able to fix the number of columns at a standard count of 80 or 132 for example. Sometimes a browser window can be so wide, that the terminal becomes too wide if autoresized to all edges.

**Comment by tsl0922** [comment]
Not possible for now, but can be implemented.
