### ISSUE TITLE
CORS error when iframed caused by window.top

### ISSUE THREAD

**Issue by sheepa** [tsl0922/ttyd#803]
When ttyd is embedded in an iframe you get a CORS error

```
Uncaught DOMException: Blocked a frame with origin "https://example.com" from accessing a cross-origin frame.
    at pe.setRendererType (https://example.com/ttyd:1:451159)
    at https://example.com/ttyd:1:451811
    at Array.forEach (<anonymous>)
    at pe.applyOptions (https://example.com/ttyd:1:451752)
    at pe.onSocketData (https://example.com/ttyd:1:453600)
```

Caused by  `window.top` at line 225 & 228 at `./ttyd/html/src/components/terminal/index.tsx`

Will not just simply replacing `window.top` with `window.self` fix this?

**Comment by tsl0922** [comment]
> How do you look at adding try/catch and fallabck to use user agent checks?

@mdevaev seems reasonable.

**Comment by tsl0922** [comment]
Should be fixed on master now (1fbb9792a66a48e99fd52b2527db877c22769ee1).

**Comment by sheepa** [comment]
It works now! Appreciate it!

**Comment by mdevaev** [comment]
@tsl0922 please don't remove `window.top` logic. The `safari` object does not exist in `window` if tyd is opened inside an iframe, and thus it will be impossible to distinguish safari from another browser. I.e. latest patch breaks the browser definition.

I meant that you can take my old logic, enclose it in try/catch, but if it doesn't work because of CORS, determine the browser by the xterm.js built-in logic. Let me make a patch for this

**Comment by mdevaev** [comment]
Please take a look: #830
